/**
 * Excel Output Data Structures
 * Defines interfaces for the ideal Excel output format
 */

/**
 * Represents a single row in the final Excel output
 * Columns: Scene # | Timecode | Screenshot | OCR Text | NA Text
 */
export interface ExcelRow {
  /** Scene number (sequential: 1, 2, 3...) */
  sceneNumber: number;

  /** Timecode in HH:MM:SS format (scene change timestamp) */
  timecode: string;

  /** Path to extracted frame PNG file */
  screenshotPath: string;

  /** Text detected by OCR (Gemini Vision) */
  ocrText: string;

  /** Narration text from audio transcription (Whisper) */
  narrationText: string;
}

/**
 * Video metadata for Excel formatting
 */
export interface VideoMetadata {
  /** Video width in pixels */
  width: number;

  /** Video height in pixels */
  height: number;

  /** Aspect ratio (width / height, e.g., 1.777 for 16:9) */
  aspectRatio: number;

  /** Total video duration in seconds */
  duration: number;
}

/**
 * Scene information from FFmpeg detection
 */
export interface Scene {
  /** Scene number (sequential: 1, 2, 3...) */
  sceneNumber: number;

  /** Scene change detection point (seconds) */
  startTime: number;

  /** Next scene change point (seconds) */
  endTime: number;

  /** Mid-point for screenshot extraction (startTime + endTime) / 2 */
  midTime: number;

  /** Timecode in HH:MM:SS format at startTime */
  timecode: string;

  /** Path to extracted screenshot (set after frame extraction) */
  screenshotPath?: string;
}

/**
 * Scene cut detection result from FFmpeg
 */
export interface SceneCut {
  /** Timestamp of scene change in seconds */
  timestamp: number;

  /** Detection confidence (FFmpeg threshold: 0.03-0.10) */
  confidence: number;

  /** Detection source: full frame, ROI, or both (NEW: ROI detection) */
  source?: 'full_frame' | 'roi_bottom' | 'roi_center' | 'roi_top_left' | 'roi_top_right' | 'both';

  /** Inferred detection reason based on source (NEW: ROI detection) */
  detectionReason?: 'scene_change' | 'subtitle_change' | 'text_overlay_change' | 'both';
}

/**
 * ROI (Region of Interest) configuration for targeted scene detection
 * Enables detection of subtitle/text changes in specific screen regions
 * Added: 2025-11-14 - MVP implementation (bottom subtitle area)
 */
export interface ROIRegion {
  /** Region identifier (e.g., 'bottom_subtitle', 'center_text', 'top_left_logo') */
  name: string;

  /** FFmpeg crop filter syntax: 'width:height:x:y'
   * Examples:
   * - Bottom 15%: 'iw:ih*0.15:0:ih*0.85'
   * - Center 15%: 'iw:ih*0.15:0:ih*0.425'
   * - Top-left 10%: 'iw*0.25:ih*0.1:0:0'
   */
  crop: string;

  /** Scene detection thresholds for this region (0.0-1.0)
   * Lower values = more sensitive (e.g., [0.01, 0.015] for subtitle changes)
   */
  thresholds: number[];

  /** Description of what this region detects (optional) */
  description?: string;
}

/**
 * ROI detection configuration
 */
export interface ROIConfig {
  /** Enable/disable ROI detection (default: false for backward compatibility) */
  enabled: boolean;

  /** Array of ROI regions to detect */
  regions: ROIRegion[];

  /** Deduplication interval in seconds (default: 0.1s)
   * Cuts closer than this interval are considered duplicates
   */
  deduplicationInterval?: number;
}

/**
 * Topic group: consecutive scenes grouped by similar OCR text
 * Generated by topicGrouping.ts after LLM cleansing
 */
export interface TopicGroup {
  /** Group number (sequential: 1, 2, 3...) */
  groupNumber: number;

  /** Scene range string (e.g., "3-7") */
  sceneRange: string;

  /** Time range string (e.g., "00:15 - 01:23") */
  timeRange: string;

  /** Number of scenes in this group */
  count: number;

  /** Representative OCR text for this group */
  ocr: string;

  /** Combined narration text for this group */
  narration: string;
}

/**
 * Excel generation options
 */
export interface ExcelGenerationOptions {
  /** Project/video title */
  projectTitle: string;

  /** Array of Excel rows to generate */
  rows: ExcelRow[];

  /** Video metadata for image sizing */
  videoMetadata: VideoMetadata;

  /** Include processing statistics sheet (optional) */
  includeStatistics?: boolean;

  /** Topic groups for Topics sheet (optional) */
  topicGroups?: TopicGroup[];

  /** Processing warnings to display in Statistics sheet (optional) */
  warnings?: string[];
}

/**
 * Processing statistics for Excel stats sheet
 */
export interface ProcessingStats {
  /** Total number of scenes processed */
  totalScenes: number;

  /** Number of scenes with OCR text detected */
  scenesWithOCRText: number;

  /** Number of scenes with narration */
  scenesWithNarration: number;

  /** Total processing time in milliseconds */
  processingTimeMs: number;

  /** Estimated cost (USD) */
  estimatedCost?: number;

  /** Video metadata */
  videoMetadata?: VideoMetadata;
}
